//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AVSFacturador.Complementos {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/divisas")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/divisas", IsNullable=false)]
    public partial class Divisas 
    {
        public virtual string Serialize(Divisas divisas)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
            ns.Add("divisas", "http://www.sat.gob.mx/divisas");


            xmlSerializer.Serialize(memoryStream, divisas, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out Divisas obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(Divisas));
                obj = (Divisas)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public Divisas Deserialize(string xml)
        {
            System.Exception e;
            Divisas divisas;
            if (Deserialize(xml, out divisas, out e))
            {
                return divisas;
            }
            else
            {
                throw e;
            }
        }
        
        private string versionField;
        
        private DivisasTipoOperacion tipoOperacionField;
        
        public Divisas() {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DivisasTipoOperacion tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/divisas")]
    public enum DivisasTipoOperacion {
        
        /// <remarks/>
        compra,
        
        /// <remarks/>
        venta,
    }
}
