//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AVSFacturador.Complementos {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ecc")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/ecc", IsNullable=false)]
    public partial class EstadoDeCuentaCombustible 
    {
        public virtual string Serialize(EstadoDeCuentaCombustible estadodecuentacombustible)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
            ns.Add("ecc", "http://www.sat.gob.mx/ecc");

            xmlSerializer.Serialize(memoryStream, estadodecuentacombustible, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out EstadoDeCuentaCombustible obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(EstadoDeCuentaCombustible));
                obj = (EstadoDeCuentaCombustible)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public EstadoDeCuentaCombustible Deserialize(string xml)
        {
            System.Exception e;
            EstadoDeCuentaCombustible estadodecuenta;
            if (Deserialize(xml, out estadodecuenta, out e))
            {
                return estadodecuenta;
            }
            else
            {
                throw e;
            }
        }

        private EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustible[] conceptosField;
        
        private string tipoOperacionField;
        
        private string numeroDeCuentaField;
        
        private decimal subTotalField;
        
        private bool subTotalFieldSpecified;
        
        private decimal totalField;
        
        public EstadoDeCuentaCombustible() {
            this.tipoOperacionField = "Tarjeta";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ConceptoEstadoDeCuentaCombustible", IsNullable=false)]
        public EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustible[] Conceptos {
            get {
                return this.conceptosField;
            }
            set {
                this.conceptosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numeroDeCuenta {
            get {
                return this.numeroDeCuentaField;
            }
            set {
                this.numeroDeCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal subTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subTotalSpecified {
            get {
                return this.subTotalFieldSpecified;
            }
            set {
                this.subTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ecc")]
    public partial class EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustible {
        
        private EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTraslado[] trasladosField;
        
        private string identificadorField;
        
        private System.DateTime fechaField;
        
        private string rfcField;
        
        private string claveEstacionField;
        
        private decimal cantidadField;
        
        private string nombreCombustibleField;
        
        private string folioOperacionField;
        
        private decimal valorUnitarioField;
        
        private decimal importeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable=false)]
        public EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTraslado[] Traslados {
            get {
                return this.trasladosField;
            }
            set {
                this.trasladosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string claveEstacion {
            get {
                return this.claveEstacionField;
            }
            set {
                this.claveEstacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nombreCombustible {
            get {
                return this.nombreCombustibleField;
            }
            set {
                this.nombreCombustibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string folioOperacion {
            get {
                return this.folioOperacionField;
            }
            set {
                this.folioOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal valorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ecc")]
    public partial class EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTraslado {
        
        private EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTrasladoImpuesto impuestoField;
        
        private decimal tasaField;
        
        private decimal importeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTrasladoImpuesto impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal tasa {
            get {
                return this.tasaField;
            }
            set {
                this.tasaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ecc")]
    public enum EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTrasladoImpuesto {
        
        /// <remarks/>
        IVA,
        
        /// <remarks/>
        IEPS,
    }
}
