//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AVSFacturador.Complementos {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/iedu")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/iedu", IsNullable=false)]
    public partial class instEducativas 
    {
        public virtual string Serialize(instEducativas insteducativas)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
            ns.Add("iedu", "http://www.sat.gob.mx/iedu");

            xmlSerializer.Serialize(memoryStream, insteducativas, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out instEducativas obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(instEducativas));
                obj = (instEducativas)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public instEducativas Deserialize(string xml)
        {
            System.Exception e;
            instEducativas insteducativas;
            if (Deserialize(xml, out insteducativas, out e))
            {
                return insteducativas;
            }
            else
            {
                throw e;
            }
        }
        
        private string versionField;
        
        private string nombreAlumnoField;
        
        private string cURPField;
        
        private instEducativasNivelEducativo nivelEducativoField;
        
        private string autRVOEField;
        
        private string rfcPagoField;
        
        public instEducativas() {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nombreAlumno {
            get {
                return this.nombreAlumnoField;
            }
            set {
                this.nombreAlumnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CURP {
            get {
                return this.cURPField;
            }
            set {
                this.cURPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public instEducativasNivelEducativo nivelEducativo {
            get {
                return this.nivelEducativoField;
            }
            set {
                this.nivelEducativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string autRVOE {
            get {
                return this.autRVOEField;
            }
            set {
                this.autRVOEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rfcPago {
            get {
                return this.rfcPagoField;
            }
            set {
                this.rfcPagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/iedu")]
    public enum instEducativasNivelEducativo {
        
        /// <remarks/>
        Preescolar,
        
        /// <remarks/>
        Primaria,
        
        /// <remarks/>
        Secundaria,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Profesional técnico")]
        Profesionaltécnico,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Bachillerato o su equivalente")]
        Bachilleratoosuequivalente,
    }
}
