//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVSFacturador.Complementos
{

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/ine")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/ine", IsNullable = false)]
    public partial class INE
    {
        public virtual string Serialize(INE ine)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
            ns.Add("ine", "http://www.sat.gob.mx/ine");

            xmlSerializer.Serialize(memoryStream, ine, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out INE obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(INE));
                obj = (INE)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public INE Deserialize(string xml)
        {
            System.Exception e;
            INE ine;
            if (Deserialize(xml, out ine, out e))
            {
                return ine;
            }
            else
            {
                throw e;
            }
        }

        private INEEntidad[] entidadField;

        private string versionField;

        private INETipoProceso tipoProcesoField;

        private INETipoComite tipoComiteField;

        private bool tipoComiteFieldSpecified;

        private int idContabilidadField;

        private bool idContabilidadFieldSpecified;

        public INE()
        {
            this.versionField = "1.1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entidad")]
        public INEEntidad[] Entidad
        {
            get
            {
                return this.entidadField;
            }
            set
            {
                this.entidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public INETipoProceso TipoProceso
        {
            get
            {
                return this.tipoProcesoField;
            }
            set
            {
                this.tipoProcesoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public INETipoComite TipoComite
        {
            get
            {
                return this.tipoComiteField;
            }
            set
            {
                this.tipoComiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoComiteSpecified
        {
            get
            {
                return this.tipoComiteFieldSpecified;
            }
            set
            {
                this.tipoComiteFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdContabilidad
        {
            get
            {
                return this.idContabilidadField;
            }
            set
            {
                this.idContabilidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdContabilidadSpecified
        {
            get
            {
                return this.idContabilidadFieldSpecified;
            }
            set
            {
                this.idContabilidadFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/ine")]
    public partial class INEEntidad
    {

        private INEEntidadContabilidad[] contabilidadField;

        private t_ClaveEntidad claveEntidadField;

        private INEEntidadAmbito ambitoField;

        private bool ambitoFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contabilidad")]
        public INEEntidadContabilidad[] Contabilidad
        {
            get
            {
                return this.contabilidadField;
            }
            set
            {
                this.contabilidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public t_ClaveEntidad ClaveEntidad
        {
            get
            {
                return this.claveEntidadField;
            }
            set
            {
                this.claveEntidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public INEEntidadAmbito Ambito
        {
            get
            {
                return this.ambitoField;
            }
            set
            {
                this.ambitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmbitoSpecified
        {
            get
            {
                return this.ambitoFieldSpecified;
            }
            set
            {
                this.ambitoFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/ine")]
    public partial class INEEntidadContabilidad
    {

        private int idContabilidadField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdContabilidad
        {
            get
            {
                return this.idContabilidadField;
            }
            set
            {
                this.idContabilidadField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/ine")]
    public enum t_ClaveEntidad
    {

        /// <remarks/>
        AGU,

        /// <remarks/>
        BCN,

        /// <remarks/>
        BCS,

        /// <remarks/>
        CAM,

        /// <remarks/>
        CHP,

        /// <remarks/>
        CHH,

        /// <remarks/>
        COA,

        /// <remarks/>
        COL,

        /// <remarks/>
        CR1,

        /// <remarks/>
        CR2,

        /// <remarks/>
        CR3,

        /// <remarks/>
        CR4,

        /// <remarks/>
        CR5,

        /// <remarks/>
        DIF,

        /// <remarks/>
        DUR,

        /// <remarks/>
        GUA,

        /// <remarks/>
        GRO,

        /// <remarks/>
        HID,

        /// <remarks/>
        JAL,

        /// <remarks/>
        MEX,

        /// <remarks/>
        MIC,

        /// <remarks/>
        MOR,

        /// <remarks/>
        NAC,

        /// <remarks/>
        NAY,

        /// <remarks/>
        NLE,

        /// <remarks/>
        OAX,

        /// <remarks/>
        PUE,

        /// <remarks/>
        QUE,

        /// <remarks/>
        ROO,

        /// <remarks/>
        SLP,

        /// <remarks/>
        SIN,

        /// <remarks/>
        SON,

        /// <remarks/>
        TAB,

        /// <remarks/>
        TAM,

        /// <remarks/>
        TLA,

        /// <remarks/>
        VER,

        /// <remarks/>
        YUC,

        /// <remarks/>
        ZAC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/ine")]
    public enum INEEntidadAmbito
    {

        /// <remarks/>
        Local,

        /// <remarks/>
        Federal,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/ine")]
    public enum INETipoProceso
    {

        /// <remarks/>
        Ordinario,

        /// <remarks/>
        Precampaña,

        /// <remarks/>
        Campaña,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/ine")]
    public enum INETipoComite
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ejecutivo Nacional")]
        EjecutivoNacional,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ejecutivo Estatal")]
        EjecutivoEstatal,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Directivo Estatal")]
        DirectivoEstatal,
    }
}