//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AVSFacturador.Complementos {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/leyendasFiscales")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/leyendasFiscales", IsNullable=false)]
    public partial class LeyendasFiscales 
    {
        public virtual string Serialize(LeyendasFiscales leyendasfiscales)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
            ns.Add("leyendasFisc", "http://www.sat.gob.mx/leyendasFiscales");

            xmlSerializer.Serialize(memoryStream, leyendasfiscales, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out LeyendasFiscales obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(LeyendasFiscales));
                obj = (LeyendasFiscales)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public LeyendasFiscales Deserialize(string xml)
        {
            System.Exception e;
            LeyendasFiscales leyendasfiscales;
            if (Deserialize(xml, out leyendasfiscales, out e))
            {
                return leyendasfiscales;
            }
            else
            {
                throw e;
            }
        }
        
        private LeyendasFiscalesLeyenda[] leyendaField;
        
        private string versionField;
        
        public LeyendasFiscales() {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leyenda")]
        public LeyendasFiscalesLeyenda[] Leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/leyendasFiscales")]
    public partial class LeyendasFiscalesLeyenda {
        
        private string disposicionFiscalField;
        
        private string normaField;
        
        private string textoLeyendaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disposicionFiscal {
            get {
                return this.disposicionFiscalField;
            }
            set {
                this.disposicionFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string norma {
            get {
                return this.normaField;
            }
            set {
                this.normaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string textoLeyenda {
            get {
                return this.textoLeyendaField;
            }
            set {
                this.textoLeyendaField = value;
            }
        }
    }
}
