//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVSFacturador.Complementos
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/notariospublicos", IsNullable = false)]
    public partial class NotariosPublicos
    {

        public virtual string Serialize(NotariosPublicos notariosPublicos)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
            ns.Add("notariospublicos", "http://www.sat.gob.mx/notariospublicos");

            xmlSerializer.Serialize(memoryStream, notariosPublicos, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out NotariosPublicos obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(NotariosPublicos));
                obj = (NotariosPublicos)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public NotariosPublicos Deserialize(string xml)
        {
            System.Exception e;
            NotariosPublicos notariosPublicos;
            if (Deserialize(xml, out notariosPublicos, out e))
            {
                return notariosPublicos;
            }
            else
            {
                throw e;
            }
        }

        private NotariosPublicosDescInmueble[] descInmueblesField;

        private NotariosPublicosDatosOperacion datosOperacionField;

        private NotariosPublicosDatosNotario datosNotarioField;

        private NotariosPublicosDatosEnajenante datosEnajenanteField;

        private NotariosPublicosDatosAdquiriente datosAdquirienteField;

        private string versionField;

        public NotariosPublicos()
        {
            this.versionField = "1.0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DescInmueble", IsNullable = false)]
        public NotariosPublicosDescInmueble[] DescInmuebles
        {
            get
            {
                return this.descInmueblesField;
            }
            set
            {
                this.descInmueblesField = value;
            }
        }

        /// <remarks/>
        public NotariosPublicosDatosOperacion DatosOperacion
        {
            get
            {
                return this.datosOperacionField;
            }
            set
            {
                this.datosOperacionField = value;
            }
        }

        /// <remarks/>
        public NotariosPublicosDatosNotario DatosNotario
        {
            get
            {
                return this.datosNotarioField;
            }
            set
            {
                this.datosNotarioField = value;
            }
        }

        /// <remarks/>
        public NotariosPublicosDatosEnajenante DatosEnajenante
        {
            get
            {
                return this.datosEnajenanteField;
            }
            set
            {
                this.datosEnajenanteField = value;
            }
        }

        /// <remarks/>
        public NotariosPublicosDatosAdquiriente DatosAdquiriente
        {
            get
            {
                return this.datosAdquirienteField;
            }
            set
            {
                this.datosAdquirienteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDescInmueble
    {

        private string tipoInmuebleField;

        private string calleField;

        private string noExteriorField;

        private string noInteriorField;

        private string coloniaField;

        private string localidadField;

        private string referenciaField;

        private string municipioField;

        private t_EntidadFederativa estadoField;

        private string paisField;

        private string codigoPostalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoInmueble
        {
            get
            {
                return this.tipoInmuebleField;
            }
            set
            {
                this.tipoInmuebleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Calle
        {
            get
            {
                return this.calleField;
            }
            set
            {
                this.calleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NoExterior
        {
            get
            {
                return this.noExteriorField;
            }
            set
            {
                this.noExteriorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NoInterior
        {
            get
            {
                return this.noInteriorField;
            }
            set
            {
                this.noInteriorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Colonia
        {
            get
            {
                return this.coloniaField;
            }
            set
            {
                this.coloniaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Municipio
        {
            get
            {
                return this.municipioField;
            }
            set
            {
                this.municipioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public t_EntidadFederativa Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Pais
        {
            get
            {
                return this.paisField;
            }
            set
            {
                this.paisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodigoPostal
        {
            get
            {
                return this.codigoPostalField;
            }
            set
            {
                this.codigoPostalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public enum t_EntidadFederativa
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28")]
        Item28,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosOperacion
    {

        private int numInstrumentoNotarialField;

        private System.DateTime fechaInstNotarialField;

        private decimal montoOperacionField;

        private decimal subtotalField;

        private decimal iVAField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumInstrumentoNotarial
        {
            get
            {
                return this.numInstrumentoNotarialField;
            }
            set
            {
                this.numInstrumentoNotarialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime FechaInstNotarial
        {
            get
            {
                return this.fechaInstNotarialField;
            }
            set
            {
                this.fechaInstNotarialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MontoOperacion
        {
            get
            {
                return this.montoOperacionField;
            }
            set
            {
                this.montoOperacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.subtotalField;
            }
            set
            {
                this.subtotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal IVA
        {
            get
            {
                return this.iVAField;
            }
            set
            {
                this.iVAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosNotario
    {

        private string cURPField;

        private int numNotariaField;

        private t_EntidadFederativa entidadFederativaField;

        private string adscripcionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CURP
        {
            get
            {
                return this.cURPField;
            }
            set
            {
                this.cURPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumNotaria
        {
            get
            {
                return this.numNotariaField;
            }
            set
            {
                this.numNotariaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public t_EntidadFederativa EntidadFederativa
        {
            get
            {
                return this.entidadFederativaField;
            }
            set
            {
                this.entidadFederativaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Adscripcion
        {
            get
            {
                return this.adscripcionField;
            }
            set
            {
                this.adscripcionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosEnajenante
    {

        private object itemField;

        private NotariosPublicosDatosEnajenanteCoproSocConyugalE coproSocConyugalEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatosEnajenantesCopSC", typeof(NotariosPublicosDatosEnajenanteDatosEnajenantesCopSC))]
        [System.Xml.Serialization.XmlElementAttribute("DatosUnEnajenante", typeof(NotariosPublicosDatosEnajenanteDatosUnEnajenante))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NotariosPublicosDatosEnajenanteCoproSocConyugalE CoproSocConyugalE
        {
            get
            {
                return this.coproSocConyugalEField;
            }
            set
            {
                this.coproSocConyugalEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosEnajenanteDatosEnajenantesCopSC
    {

        private NotariosPublicosDatosEnajenanteDatosEnajenantesCopSCDatosEnajenanteCopSC[] datosEnajenanteCopSCField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatosEnajenanteCopSC")]
        public NotariosPublicosDatosEnajenanteDatosEnajenantesCopSCDatosEnajenanteCopSC[] DatosEnajenanteCopSC
        {
            get
            {
                return this.datosEnajenanteCopSCField;
            }
            set
            {
                this.datosEnajenanteCopSCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosEnajenanteDatosEnajenantesCopSCDatosEnajenanteCopSC
    {

        private string nombreField;

        private string apellidoPaternoField;

        private string apellidoMaternoField;

        private string rFCField;

        private string cURPField;

        private decimal porcentajeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC
        {
            get
            {
                return this.rFCField;
            }
            set
            {
                this.rFCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CURP
        {
            get
            {
                return this.cURPField;
            }
            set
            {
                this.cURPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Porcentaje
        {
            get
            {
                return this.porcentajeField;
            }
            set
            {
                this.porcentajeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosEnajenanteDatosUnEnajenante
    {

        private string nombreField;

        private string apellidoPaternoField;

        private string apellidoMaternoField;

        private string rFCField;

        private string cURPField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC
        {
            get
            {
                return this.rFCField;
            }
            set
            {
                this.rFCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CURP
        {
            get
            {
                return this.cURPField;
            }
            set
            {
                this.cURPField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public enum NotariosPublicosDatosEnajenanteCoproSocConyugalE
    {

        /// <remarks/>
        Si,

        /// <remarks/>
        No,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosAdquiriente
    {

        private object itemField;

        private NotariosPublicosDatosAdquirienteCoproSocConyugalE coproSocConyugalEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatosAdquirientesCopSC", typeof(NotariosPublicosDatosAdquirienteDatosAdquirientesCopSC))]
        [System.Xml.Serialization.XmlElementAttribute("DatosUnAdquiriente", typeof(NotariosPublicosDatosAdquirienteDatosUnAdquiriente))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NotariosPublicosDatosAdquirienteCoproSocConyugalE CoproSocConyugalE
        {
            get
            {
                return this.coproSocConyugalEField;
            }
            set
            {
                this.coproSocConyugalEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosAdquirienteDatosAdquirientesCopSC
    {

        private NotariosPublicosDatosAdquirienteDatosAdquirientesCopSCDatosAdquirienteCopSC[] datosAdquirienteCopSCField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatosAdquirienteCopSC")]
        public NotariosPublicosDatosAdquirienteDatosAdquirientesCopSCDatosAdquirienteCopSC[] DatosAdquirienteCopSC
        {
            get
            {
                return this.datosAdquirienteCopSCField;
            }
            set
            {
                this.datosAdquirienteCopSCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosAdquirienteDatosAdquirientesCopSCDatosAdquirienteCopSC
    {

        private string nombreField;

        private string apellidoPaternoField;

        private string apellidoMaternoField;

        private string rFCField;

        private string cURPField;

        private decimal porcentajeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC
        {
            get
            {
                return this.rFCField;
            }
            set
            {
                this.rFCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CURP
        {
            get
            {
                return this.cURPField;
            }
            set
            {
                this.cURPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Porcentaje
        {
            get
            {
                return this.porcentajeField;
            }
            set
            {
                this.porcentajeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public partial class NotariosPublicosDatosAdquirienteDatosUnAdquiriente
    {

        private string nombreField;

        private string apellidoPaternoField;

        private string apellidoMaternoField;

        private string rFCField;

        private string cURPField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC
        {
            get
            {
                return this.rFCField;
            }
            set
            {
                this.rFCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CURP
        {
            get
            {
                return this.cURPField;
            }
            set
            {
                this.cURPField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/notariospublicos")]
    public enum NotariosPublicosDatosAdquirienteCoproSocConyugalE
    {

        /// <remarks/>
        Si,

        /// <remarks/>
        No,
    }
}