//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AVSFacturador.Complementos {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/pfic")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/pfic", IsNullable=false)]
    public partial class PFintegranteCoordinado 
    {
        public virtual string Serialize(PFintegranteCoordinado pfintegrantecoordinado)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
            ns.Add("pfic", "http://www.sat.gob.mx/pfic");

            xmlSerializer.Serialize(memoryStream, pfintegrantecoordinado, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out PFintegranteCoordinado obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(PFintegranteCoordinado));
                obj = (PFintegranteCoordinado)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public PFintegranteCoordinado Deserialize(string xml)
        {
            System.Exception e;
            PFintegranteCoordinado pfintegrante;
            if (Deserialize(xml, out pfintegrante, out e))
            {
                return pfintegrante;
            }
            else
            {
                throw e;
            }
        }
        
        private string versionField;
        
        private string claveVehicularField;
        
        private string placaField;
        
        private string rFCPFField;
        
        public PFintegranteCoordinado() {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClaveVehicular {
            get {
                return this.claveVehicularField;
            }
            set {
                this.claveVehicularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFCPF {
            get {
                return this.rFCPFField;
            }
            set {
                this.rFCPFField = value;
            }
        }
    }
}
