//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AVSFacturador.Complementos
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero", IsNullable = false)]
    public partial class TuristaPasajeroExtranjero
    {
        public virtual string Serialize(TuristaPasajeroExtranjero turistapasajeroextrangero)
        {
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
            System.IO.MemoryStream memoryStream = new System.IO.MemoryStream();
            XmlSerializerNamespaces ns = new XmlSerializerNamespaces();

            xmlSerializer.Serialize(memoryStream, turistapasajeroextrangero, ns);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            System.IO.StreamReader streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }

        public static bool Deserialize(string xml, out TuristaPasajeroExtranjero obj, out System.Exception exception)
        {
            exception = null;
            obj = null;
            try
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(xml);
                System.IO.StreamReader stringReader = new System.IO.StreamReader(new System.IO.MemoryStream(bytes));
                System.Xml.XmlTextReader xmlTextReader = new System.Xml.XmlTextReader(stringReader);

                System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(TuristaPasajeroExtranjero));
                obj = (TuristaPasajeroExtranjero)xmlSerializer.Deserialize(xmlTextReader);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public TuristaPasajeroExtranjero Deserialize(string xml)
        {
            System.Exception e;
            TuristaPasajeroExtranjero turistapasajero;
            if (Deserialize(xml, out turistapasajero, out e))
            {
                return turistapasajero;
            }
            else
            {
                throw e;
            }
        }

        private TuristaPasajeroExtranjeroDatosTransito datosTransitoField;

        private string versionField;

        private System.DateTime fechadeTransitoField;

        private TuristaPasajeroExtranjeroTipoTransito tipoTransitoField;

        public TuristaPasajeroExtranjero()
        {
            this.versionField = "1.0";
        }

        /// <remarks/>
        public TuristaPasajeroExtranjeroDatosTransito datosTransito
        {
            get
            {
                return this.datosTransitoField;
            }
            set
            {
                this.datosTransitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fechadeTransito
        {
            get
            {
                return this.fechadeTransitoField;
            }
            set
            {
                this.fechadeTransitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TuristaPasajeroExtranjeroTipoTransito tipoTransito
        {
            get
            {
                return this.tipoTransitoField;
            }
            set
            {
                this.tipoTransitoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    public partial class TuristaPasajeroExtranjeroDatosTransito
    {

        private TuristaPasajeroExtranjeroDatosTransitoVia viaField;

        private string tipoIdField;

        private string numeroIdField;

        private string nacionalidadField;

        private string empresaTransporteField;

        private string idTransporteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TuristaPasajeroExtranjeroDatosTransitoVia Via
        {
            get
            {
                return this.viaField;
            }
            set
            {
                this.viaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoId
        {
            get
            {
                return this.tipoIdField;
            }
            set
            {
                this.tipoIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroId
        {
            get
            {
                return this.numeroIdField;
            }
            set
            {
                this.numeroIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nacionalidad
        {
            get
            {
                return this.nacionalidadField;
            }
            set
            {
                this.nacionalidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmpresaTransporte
        {
            get
            {
                return this.empresaTransporteField;
            }
            set
            {
                this.empresaTransporteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdTransporte
        {
            get
            {
                return this.idTransporteField;
            }
            set
            {
                this.idTransporteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    public enum TuristaPasajeroExtranjeroDatosTransitoVia
    {

        /// <remarks/>
        Aérea,

        /// <remarks/>
        Marítima,

        /// <remarks/>
        Terrestre,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    public enum TuristaPasajeroExtranjeroTipoTransito
    {

        /// <remarks/>
        Arribo,

        /// <remarks/>
        Salida,
    }
}
